# Generated by Django 4.1.3 on 2022-11-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_formfillup_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfillup',
            name='steps',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
